services:
  mysql:
    image: mysql:8.0
    container_name: database_app
    env_file: 
      - .env
    volumes:
      - mysql-data: /var/lib/postgresql/data
  
  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: [ "/fastapi_app.docker/app.sh" ]
    ports:
      - 80:8000
    depends_on:
      - db

volumes:
  - mysql-data