services:
  mysql:
    image: mysql:8
    container_name: database_app
    env_file: 
      - .env

  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: [ "/fastapi_app/docker/app.sh" ]
    ports:
      - 80:8000
    depends_on:
      - mysql
